export const ADMIN_ROUTE = '/admin'
export const GENRE_ROUTE = '/genre'
export const TYPE_ROUTE = '/type'
export const PROFESSION_ROUTE = '/profession'
export const COUNTRY_ROUTE = '/country'
export const HUMAN_ROUTE = '/human'
export const LIST_PROFESSION_HUMAN_ROUTE = '/list_profession_human'
export const LIST_COUNTRY_ROUTE = '/list_country'
export const LIST_GENRE_ROUTE = '/list_genre'
export const LIST_COMPOSITION_HUMAN_ROUTE = '/list_composition_human'
export const USER_PROFILE_ROUTE = '/user_profile'
export const RATING_ROUTE = '/rating'
export const REVIEW_ROUTE = '/review'

export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const COMPOSITION_ROUTE = '/composition'