const Routes = require('express')
const router = new Routes()
const humanRouter = require('./humanRouter')
const userRouter = require('./userRouter')
const professionRouter = require('./professionRouter')
const compositionRouter = require('./compositionRouter')
const typeRouter = require('./typeRouter')
const genreRouter = require('./genreRouter')
const countryRouter = require('./countryRouter')
const list_profession_humanRouter = require('./list_profession_humanRouter')
const list_composition_humanRouter = require('./list_coposition_humanRouter')
const list_countryRouter = require('./list_countryRouter')
const list_genreRouter = require('./list_genreRouter')
const user_profileRouter = require('./userRouter')

router.use('/user',userRouter)
router.use('/composition',compositionRouter)
router.use('/human',humanRouter)
router.use('/profession',professionRouter)
router.use('/type',typeRouter)
router.use('/genre',genreRouter)
router.use('/country',countryRouter)
router.use('/list_profession_human',list_profession_humanRouter)
router.use('/list_composition_human',list_composition_humanRouter)
router.use('/list_country',list_countryRouter)
router.use('/list_genre',list_genreRouter)
router.use('/user_profile',user_profileRouter)

module.exports = router